config/routes.rb
Rails.application.routes.draw do
  
  resources :items
  resources :categories

  get 'welcome/index'

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@category = Category.all
	end

	def show
		@category = Category.find(params[:id])
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@item = Item.all
	end

	def show
		
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<table border=1 style="width:100%">
<% @category.each do |x| %>
	<tr>
	<td><%= x.id%></td>
	<td><%= x.name%></td>
	</tr>
<% end %>
</table>
<p><%= link_to "Main", root_url %></p>

app/views/categories/show.html.erb
<p><%= @category.name %>(<%= @category.items.count %>)</p>
<% @category.items.each do |x| %>
	<li><%= x.name %></li>
<% end %>

app/views/items/index.html.erb
<table border=1 style="width:100%">
<% @item.each do |x| %>
	<tr>
	<td><%= x.id%></td>
	<td><%= x.name %></td>
	<td><%= x.featured %></td>
	<td><%= link_to x.category_id, categories_path(x.category_id)%></td>
	</tr>
<% end %>
</table>
<p><%= link_to "Main", root_url %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hardware Datebase</h1>
<p><%= link_to "Items", items_path %></p>
<p><%= link_to "Categories", categories_path %></p>